@baseUrl = http://localhost:8080/api/v1

### REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "test",
  "email": "test3@mail.ru",
  "password": "111111"
}


### AUTHENTICATE
POST {{baseUrl}}/auth/authenticate
Content-Type: application/json

{
  "email": "test@mail.ru",
  "password": "111111"
}

### ----- AUTH TOKEN -----

@authToken = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG1haWwucnUiLCJpYXQiOjE3NDc4MTE0NzEsImV4cCI6MTc0NzgxMjkxMX0.cWGiQVVDMZMZvYSksw6zjoOvK-VsgsgYc2AYgN4r4RY

### GET ALL PAGES
GET {{baseUrl}}/page
Authorization: {{authToken}}


### GET PAGE BY ID
GET {{baseUrl}}/page/3
Authorization: {{authToken}}


### ADD PAGE
POST {{baseUrl}}/page
Authorization: {{authToken}}
Content-Type: application/json

{
  "orderInModule": 1,
  "name": "top page",
  "moduleId": 3,
  "content": "<html>"
}


### UPDATE PAGE
PUT {{baseUrl}}/page
Authorization: {{authToken}}
Content-Type: application/json

{
  "id": 1,
  "orderInModule": 1,
  "name": "top page updated",
  "moduleId": 1,
  "content": "<html> updated"
}


### DELETE PAGE
DELETE {{baseUrl}}/page/1
Authorization: {{authToken}}


### GET ALL SCOREBOARDS
GET {{baseUrl}}/scoreboard
Authorization: {{authToken}}


### GET SCOREBOARD BY ID
GET {{baseUrl}}/scoreboard/1
Authorization: {{authToken}}


### ADD SCOREBOARD
POST {{baseUrl}}/scoreboard
Content-Type: application/json
Authorization: {{authToken}}

{
  "score": 22212,
  "userId": 1
}


### UPDATE SCOREBOARD
PUT {{baseUrl}}/scoreboard
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 1,
  "userId": 1,
  "score": 99999
}


### DELETE SCOREBOARD BY ID
DELETE {{baseUrl}}/scoreboard/1
Authorization: {{authToken}}


### GET KNOWLEDGEBASES
GET {{baseUrl}}/knowledgebase
Authorization: {{authToken}}


### GET KNOWLEDGEBASE BY ID
GET {{baseUrl}}/knowledgebase/1
Authorization: {{authToken}}


### ADD KNOWLEDGEBASE
POST {{baseUrl}}/knowledgebase
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "testKnowledgeBase",
  "content": "some html content"
}


### UPDATE KNOWLEDGEBASE
PUT {{baseUrl}}/knowledgebase
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 3,
  "name": "testKnowledgeBase Updated",
  "content": "some html content Updated"
}


### DELETE KNOWLEDGEBASE BY ID
DELETE {{baseUrl}}/knowledgebase/3
Content-Type: application/json
Authorization: {{authToken}}


### GET ALL SURVEYS
GET {{baseUrl}}/survey
Authorization: {{authToken}}


### GET SURVEY BY ID
GET {{baseUrl}}/survey/2
Authorization: {{authToken}}


### ADD SURVEY
POST {{baseUrl}}/survey
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "top Survey",
  "content": "top survey content"
}


### UPDATE SURVEY
PUT {{baseUrl}}/survey
Content-Type: application/json
Authorization: {{authToken}}

{
  "id" : 6,
  "name": "top Survey updated",
  "content": "top survey content updated"
}


### DELETE SURVEY
DELETE {{baseUrl}}/survey/6
Content-Type: application/json
Authorization: {{authToken}}


### GET ALL USERS FOR SURVEY BY ID
GET {{baseUrl}}/surveys/2/users
Authorization: {{authToken}}


### ADD USER TO SURVEY
POST {{baseUrl}}/surveys/2/users/1
Authorization: {{authToken}}


### DELETE USER FROM SURVEY
DELETE {{baseUrl}}/surveys/2/users/1
Authorization: {{authToken}}


### GET ALL USERS-PROGRESES-IN-MODULES
GET {{baseUrl}}/user-progress-in-module
Authorization: {{authToken}}

### GET USER-PROGRESS-IN-MODULE BY ID
GET {{baseUrl}}/user-progress-in-module/4
Authorization: {{authToken}}


### ADD USER-PROGRESS-IN-MODULE
POST {{baseUrl}}/user-progress-in-module
Content-Type: application/json
Authorization: {{authToken}}

{
  "userId": 1,
  "moduleId": 1,
  "lastCompletedPageNumber": 3,
  "name": "progress test test"
}


### UPDATE USER-PROGRESS-IN-MODULE
PUT {{baseUrl}}/user-progress-in-module
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 5,
  "userId": 1,
  "moduleId": 1,
  "lastCompletedPageNumber": 2,
  "name": "progress update"
}


### DELTE USER-PROGRESS-IN-MODULE
DELETE {{baseUrl}}/user-progress-in-module/5
Authorization: {{authToken}}


### GET ALL MODULES
GET {{baseUrl}}/module
Content-Type: application/json
Authorization: {{authToken}}


### GET MODULE BY ID
GET {{baseUrl}}/module/1
Authorization: {{authToken}}

### ADD MODULE
POST {{baseUrl}}/module
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "top module",
  "startContent": "<html>",
  "endContent": "<html>",
  "orderInTrack": 1,
  "trackId": 1,
  "pagesCount": 10
}


### UPDATE MODULE
PUT {{baseUrl}}/module
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 2,
  "name": "top module",
  "startContent": "<html> updated",
  "endContent": "<html> updated",
  "orderInTrack": 3,
  "trackId": 1
}


### GET ALL TRACKS
GET {{baseUrl}}/track
Content-Type: application/json
Authorization: {{authToken}}


### ADD TRACK
POST {{baseUrl}}/track
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "top track"
}


### UPDATE TRACK
PUT {{baseUrl}}/track
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 1,
  "name": "top track update"
}


### DELETE TRACK
DELETE {{baseUrl}}/track/3
Authorization: {{authToken}}


### CREATE ACHIEVEMENT FOR FINISHING MODULE
POST {{baseUrl}}/achievement
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Первые шаги",
  "description": "Завершите первый модуль обучения",
  "picture": "achievement_first_steps.jpg",
  "actionType": "COMPLETE_MODULE",
  "condition": "{\"moduleId\": 1}",
  "pointsReward": 50
}


### CREATE ACHIEVEMENT FOR FIRST 100 SCORED POINTS
POST {{baseUrl}}/achievement
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Начинающий ученик",
  "description": "Накопите 100 очков в системе",
  "picture": "achievement_100_points.jpg",
  "actionType": "SCORE_THRESHOLD",
  "condition": "{\"minScore\": 100}",
  "pointsReward": 20
}


### CREATE ACHIEVEMENT FOR 7 DAYS LOGIN STREAK
POST {{baseUrl}}/achievement
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Недельная активность",
  "description": "Занимайтесь 7 дней подряд",
  "picture": "achievement_week_streak.jpg",
  "actionType": "DAYS_STREAK",
  "condition": "{\"minDays\": 7}",
  "pointsReward": 100
}


### GET ALL ACHIEVEMENTS
GET {{baseUrl}}/achievement
Authorization: {{authToken}}


### GET ACHIEVEMENT BY ID
# После выполнения запроса на создание ачивки, получите ID из ответа
# и подставьте в этот запрос
GET {{baseUrl}}/achievement/3
Authorization: {{authToken}}


### ACTION: COMPLETE MODULE
POST {{baseUrl}}/achievement/action
Content-Type: application/json
Authorization: {{authToken}}

{
  "userId": 1,
  "actionType": "COMPLETE_MODULE",
  "metadata": {
    "moduleId": 1
  }
}


### ACTION: SCORE_THRESHOLD
POST {{baseUrl}}/achievement/action
Content-Type: application/json
Authorization: {{authToken}}

{
  "userId": 1,
  "actionType": "SCORE_THRESHOLD"
}


### ACTION: 7 DAYS LOGIN STREAK
POST {{baseUrl}}/achievement/action
Content-Type: application/json
Authorization: {{authToken}}

{
  "userId": 1,
  "actionType": "DAYS_STREAK",
  "metadata": {
    "daysStreak": 7
  }
}


### GET ALL ACHIEVEMENTS
GET {{baseUrl}}/achievement/user/1
Content-Type: application/json
Authorization: {{authToken}}


### UPDATE ACHIEVEMET
PUT {{baseUrl}}/achievement
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 1,
  "name": "Первые шаги (обновлено)",
  "description": "Завершите первый модуль обучения, чтобы начать свой путь!",
  "picture": "achievement_first_steps_v2.jpg",
  "actionType": "COMPLETE_MODULE",
  "condition": "{\"moduleId\": 1}",
  "pointsReward": 75
}


### DELETE ACHIEVEMENT
DELETE {{baseUrl}}/achievement/3
Authorization: {{authToken}}
